---
title: "Weekly Assignment 2"
author: "Thomas Walsh"
date: "2023-01-21"
output:
  html_document: default
  pdf_document: default
---



```{r}
myFunc <- function(meanControl=NULL, meanTreatment=NULL){
Type <- c(rep("Control", 25), rep("Treatment", 25))
Value <- c(rnorm(25, mean=10, sd=1.5), rnorm(25, mean=45, sd=2))
dF <- data.frame(Type, Value, stringsAsFactors = FALSE)
meanControl <- mean(Value[1:25])
meanTreatment <- mean(Value[26:50])  
return(dF)
}

dataFrame <- myFunc()
head(dataFrame)


summary(aov(dataFrame$Value~dataFrame$Type, data=dataFrame))
 
 myFunc2 <- function(meanControl2=NULL, meanTreatment2=NULL){
   Type2 <- c(rep("Control2", 25), rep("Treatment2", 25))
Value2 <- c(rnorm(25, mean=10, sd=1.5), rnorm(25, mean=45, sd=2))
dF2 <- data.frame(Type2, Value2, stringsAsFactors = FALSE)
meanControl2 <- mean(Value2[1:25])
meanTreatment2 <- mean(Value2[26:50]) 
sum<-summary(aov(dF2$Value2~dF2$Type2, data=dF2))
final<-sum[[1]][["Pr(>F)"]][1]
return(final)
}
 myFunc2()

```


Edited code below:
```{r}

set.seed(123)
myFunc <- function(meanC=10, sdC=1.5, meanT = 45, sdT=2, n=25){
Type <- c(rep("Control", n), rep("Treatment", n))
Value <- c(rnorm(n, mean=meanC, sd=sdC), rnorm(n, mean=meanT, sd=sdT))
dF <- data.frame(Type, Value, stringsAsFactors = FALSE)
return(dF)
}

dataFrame <- myFunc()
head(dataFrame)


summary(aov(dataFrame$Value~dataFrame$Type, data=dataFrame))
 
 myFunc2 <- function(df=NULL){
sum<-summary(aov(Value~Type, data=df))
final<-sum[[1]][["Pr(>F)"]][1]
return(final)
}
 myFunc2(df=dataFrame)
 
 myFunc2(myFunc())
 
```

